"""Renderers for a ModelDiff (plan §J4), mirroring mdl_reverse.render.

Three surfaces, one source of truth:
  render_json     - the wire shape for the diff API AND `mdl diff --format json`
  render_text     - the terminal
  render_markdown - the PR body

The PR body matters more than it looks. `/api/git/propose` used to paste the
client's flat "- Definition: 'x' -> 'y'" list into the pull request. Generating it
from the real diff means a reviewer who never opens Modelith still sees a grouped,
severity-tagged, per-object summary — the same argument mdl_reverse.render already
makes for drift.
"""

from __future__ import annotations

from mdl_core.diff import ModelDiff, ObjectChange
from mdl_core.severity import ChangeSeverity

_EMOJI = {
    ChangeSeverity.breaking: "🔴",
    ChangeSeverity.additive: "🟢",
    ChangeSeverity.cosmetic: "⚪",
    ChangeSeverity.unmanaged: "🟡",
}
_MARK = {"added": "+", "removed": "−", "modified": "~"}


def render_json(diff: ModelDiff) -> dict:
    return diff.to_doc()


def _headline(diff: ModelDiff) -> str:
    c = diff.counts()
    bits = []
    for k in ("added", "removed", "modified"):
        if c[k]:
            bits.append(f"{c[k]} {k}")
    if not bits:
        return "no changes"
    out = ", ".join(bits)
    if c.get("breaking"):
        out += f" · {c['breaking']} breaking"
    return out


def _obj_line(o: ObjectChange) -> str:
    name = f"{o.name_before} → {o.name_after}" if o.renamed else o.display_name
    return f"{_MARK[o.change.value]} {name} ({o.object_kind.replace('_', ' ')})"


def render_text(diff: ModelDiff) -> str:
    lines = [f"{diff.base_label} → {diff.head_label}: {_headline(diff)}", ""]
    if not diff:
        return lines[0] + "\n"
    for o in diff.objects:
        lines.append(f"{_EMOJI[o.severity]} {_obj_line(o)}")
        for f in o.fields:
            detail = f" — {f.detail}" if f.detail else ""
            lines.append(f"    {f.label}{detail}")
        for c in o.children:
            for f in c.fields:
                detail = f" — {f.detail}" if f.detail else ""
                lines.append(f"    {f.label}: {c.display_name}{detail}")
    for f in diff.config:
        lines.append(f"{_EMOJI[f.severity]} {f.label} — {f.detail}")
    return "\n".join(lines) + "\n"


def render_markdown(diff: ModelDiff) -> str:
    if not diff:
        return f"No model changes between `{diff.base_label}` and `{diff.head_label}`.\n"

    out = [
        "### Model changes",
        "",
        f"`{diff.base_label}` → `{diff.head_label}` · {_headline(diff)}",
        "",
    ]
    if diff.has_breaking:
        out += [
            "> [!WARNING]",
            "> This proposal contains **breaking** changes. Review the marked objects.",
            "",
        ]
    for o in diff.objects:
        name = f"{o.name_before} → **{o.name_after}**" if o.renamed else f"**{o.display_name}**"
        out.append(
            f"{_EMOJI[o.severity]} {name} "
            f"<sub>{o.object_kind.replace('_', ' ')}</sub>"
        )
        for f in o.fields:
            detail = f" — {f.detail}" if f.detail else ""
            out.append(f"- {f.label}{detail}")
        for c in o.children:
            for f in c.fields:
                detail = f" — {f.detail}" if f.detail else ""
                out.append(f"- {f.label}: `{c.display_name}`{detail}")
        out.append("")
    if diff.config:
        out.append("**Project settings**")
        for f in diff.config:
            out.append(f"- {f.label} — {f.detail}")
        out.append("")
    out.append("<sub>Generated by `mdl` from the model, not from the YAML diff.</sub>")
    return "\n".join(out) + "\n"
