"""Pydantic v2 data-model emitter.

One `BaseModel` subclass per managed logical entity, one field per attribute, for
use by Python agents and services. This emits *data* models (rows of the modelled
entities), distinct from `mdl export json-schema`, which emits schemas for the
Modelith authoring YAML itself.

Field types come from the attribute's domain base type; enumerated domains become
`Literal[...]`; nullable attributes become `Optional[...]` with a `None` default.
"""

from __future__ import annotations

import keyword
import re

from mdl_core.ir import Model
from mdl_emit_pydantic.types import imports_for, python_type

_HEADER = '"""Generated by Modelith (mdl emit pydantic). Do not edit by hand."""'


def _class_name(name: str) -> str:
    """Entity name -> a valid PascalCase Python class identifier."""
    parts = re.split(r"[^0-9a-zA-Z]+", name)
    cls = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not cls or not cls[0].isalpha():
        cls = "Model" + cls
    return cls


def _field_name(name: str) -> str:
    """Attribute name -> a safe Python field identifier."""
    ident = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_")
    if not ident or ident[0].isdigit():
        ident = "f_" + ident
    if keyword.iskeyword(ident):
        ident += "_"
    return ident


def _literal_values(model: Model, attr) -> list | None:
    dom = model.domain_by_name(attr.domain)
    if dom is None:
        return None
    if dom.allowed_values:
        return list(dom.allowed_values)
    if dom.value_set:
        cs = model.code_set_by_name(dom.value_set)
        if cs is not None:
            return [cv.code for cv in cs.values]
    return None


def emit_pydantic_models(model: Model) -> str:
    used_python_types: set[str] = set()
    uses_literal = False
    uses_optional = False
    class_blocks: list[str] = []

    for le in sorted(model.logical_entities.values(), key=lambda e: e.name):
        if le.unmanaged:
            continue
        lines = [f"class {_class_name(le.name)}(BaseModel):"]
        if not le.attributes:
            lines.append("    pass")
        for attr in le.attributes:
            dom = model.domain_by_name(attr.domain)
            base = dom.base_type if dom else None
            values = _literal_values(model, attr)
            if values is not None:
                rendered = ", ".join(repr(v) for v in values)
                type_expr = f"Literal[{rendered}]"
                uses_literal = True
            else:
                type_expr = python_type(base)
                used_python_types.add(type_expr)
            if attr.nullable:
                type_expr = f"Optional[{type_expr}]"
                uses_optional = True
                suffix = " = None"
            else:
                suffix = ""
            lines.append(f"    {_field_name(attr.name)}: {type_expr}{suffix}")
        class_blocks.append("\n".join(lines))

    typing_imports = []
    if uses_optional:
        typing_imports.append("Optional")
    if uses_literal:
        typing_imports.append("Literal")

    # Note: no `from __future__ import annotations`. Pydantic must evaluate the
    # annotations (Optional/Literal/datetime) at class-definition time; stringized
    # annotations would require a model_rebuild() the consumer should not need.
    header_lines = [_HEADER, ""]
    for imp in imports_for(used_python_types):
        header_lines.append(imp)
    if typing_imports:
        header_lines.append(f"from typing import {', '.join(typing_imports)}")
    header_lines.append("")
    header_lines.append("from pydantic import BaseModel")
    header_lines.append("")
    header_lines.append("")

    body = "\n\n\n".join(class_blocks) if class_blocks else "# no managed entities"
    return "\n".join(header_lines) + body + "\n"
