"""Neo4j / Cypher schema emitter.

Emit a Cypher schema script from the logical model: node uniqueness / node-key
constraints from primary and unique key groups, property-existence constraints from
non-nullable attributes, and directed relationship types from the model's
relationships. Genuinely novel: neither LinkML nor datacontract-cli emits Cypher.

Targets Neo4j 5 constraint syntax:
  CREATE CONSTRAINT ... IF NOT EXISTS FOR (n:Label) REQUIRE n.prop IS UNIQUE
  CREATE CONSTRAINT ... IF NOT EXISTS FOR (n:Label) REQUIRE (n.a, n.b) IS NODE KEY
  CREATE CONSTRAINT ... IF NOT EXISTS FOR (n:Label) REQUIRE n.prop IS NOT NULL
"""

from __future__ import annotations

import re

from mdl_core.ir import Model
from mdl_emit_graph.types import neo4j_type


def _label(name: str) -> str:
    """Entity name -> a PascalCase Neo4j node label."""
    parts = re.split(r"[^0-9a-zA-Z]+", name)
    lbl = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return lbl or "Node"


def _rel_type(name: str) -> str:
    """Relationship name -> an UPPER_SNAKE Neo4j relationship type."""
    return re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_").upper() or "REL"


def _constraint_name(*parts: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", "_".join(parts)).strip("_").lower()


def emit_cypher(model: Model) -> str:
    lines: list[str] = [
        "// Generated by Modelith (mdl export graph). Neo4j 5 constraint syntax.",
        "",
    ]

    attr_name = {}  # attribute ULID -> name, per entity
    for le in model.logical_entities.values():
        for a in le.attributes:
            attr_name[a.id] = a.name

    for le in sorted(model.logical_entities.values(), key=lambda e: e.name):
        if le.unmanaged:
            continue
        label = _label(le.name)
        lines.append(f"// ({label})  <- {le.name}")

        # Property-type reference (comment) so the target types are visible.
        for attr in le.attributes:
            dom = model.domain_by_name(attr.domain)
            base = dom.base_type if dom else None
            lines.append(f"//   {attr.name}: {neo4j_type(base)}")

        # Key groups -> node key / unique constraints.
        for kg in sorted(
            (k for k in model.key_groups.values() if k.entity == le.id),
            key=lambda k: k.name,
        ):
            props = [attr_name[m] for m in kg.members if m in attr_name]
            if not props:
                continue
            cname = _constraint_name(label, kg.name)
            prop_refs = ", ".join(f"n.{p}" for p in props)
            if kg.type == "pk":
                if len(props) == 1:
                    lines.append(
                        f"CREATE CONSTRAINT {cname} IF NOT EXISTS "
                        f"FOR (n:{label}) REQUIRE n.{props[0]} IS NODE KEY;"
                    )
                else:
                    lines.append(
                        f"CREATE CONSTRAINT {cname} IF NOT EXISTS "
                        f"FOR (n:{label}) REQUIRE ({prop_refs}) IS NODE KEY;"
                    )
            elif kg.type in ("alternate", "unique"):
                if len(props) == 1:
                    lines.append(
                        f"CREATE CONSTRAINT {cname} IF NOT EXISTS "
                        f"FOR (n:{label}) REQUIRE n.{props[0]} IS UNIQUE;"
                    )
                else:
                    lines.append(
                        f"CREATE CONSTRAINT {cname} IF NOT EXISTS "
                        f"FOR (n:{label}) REQUIRE ({prop_refs}) IS UNIQUE;"
                    )

        # Non-null attributes -> existence constraints.
        for attr in le.attributes:
            if not attr.nullable:
                cname = _constraint_name(label, attr.name, "exists")
                lines.append(
                    f"CREATE CONSTRAINT {cname} IF NOT EXISTS "
                    f"FOR (n:{label}) REQUIRE n.{attr.name} IS NOT NULL;"
                )
        lines.append("")

    # Relationships: directed types between node labels.
    rels = sorted(model.relationships.values(), key=lambda r: r.name)
    if rels:
        lines.append("// Relationships")
        for rel in rels:
            from_le = model.logical_entities.get(rel.from_.entity)
            to_le = model.logical_entities.get(rel.to.entity)
            if from_le is None or to_le is None:
                continue
            lines.append(
                f"// (:{_label(from_le.name)})-[:{_rel_type(rel.name)}]->"
                f"(:{_label(to_le.name)})  // {rel.cardinality}"
            )
        lines.append("")

    return "\n".join(lines)
