"""Emit DBML (dbdiagram.io / Holistics) from the neutral ER view.

DBML is the de-facto "ER-as-code" exchange language among modeling/diagram tools: it
opens directly in dbdiagram.io, dbdocs, and ChartDB, and converts to SQL via
@dbml/core. It carries PK/FK and cardinality (via `Ref`), so it round-trips entities,
attributes, keys, and relationships well."""

from __future__ import annotations

import re

from mdl_core.ir import Model
from mdl_emit_erd.model_view import build_tables


def _ident(name: str) -> str:
    """A DBML identifier; quote with double quotes if not a plain identifier."""
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        return name
    return f'"{name}"'


def emit_dbml(model: Model) -> str:
    from mdl_emit_dbt.platforms import get_adapter

    tables = build_tables(model, get_adapter("duckdb"))
    out: list[str] = ["// DBML generated by Modelith (https://dbml.dbdiagram.io)", ""]

    for t in tables:
        out.append(f"Table {_ident(t.name)} {{")
        composite_pk = len(t.pk_columns) > 1
        for c in t.columns:
            settings: list[str] = []
            if c.pk and not composite_pk:
                settings.append("pk")
            if c.unique and not c.pk:
                settings.append("unique")
            if not c.nullable:
                settings.append("not null")
            if c.definition:
                note = c.definition.replace("'", "").strip()
                settings.append(f"note: '{note}'")
            suffix = f" [{', '.join(settings)}]" if settings else ""
            out.append(f"  {_ident(c.name)} {c.base_type}{suffix}")
        if composite_pk:
            out.append("  indexes {")
            cols = ", ".join(_ident(c) for c in t.pk_columns)
            out.append(f"    ({cols}) [pk]")
            out.append("  }")
        if t.definition:
            note = t.definition.replace("'", "").strip()
            out.append(f"  Note: '{note}'")
        out.append("}")
        out.append("")

    # Refs: child.col > parent.col  ('>' = many-to-one, '-' = one-to-one)
    for t in tables:
        for fk in t.foreign_keys:
            if not fk.ref_columns:
                continue
            op = "-" if fk.child_unique else ">"
            # DBML refs are per-column; emit one Ref per paired column
            for cc, pc in zip(fk.columns, fk.ref_columns, strict=False):
                out.append(
                    f"Ref: {_ident(t.name)}.{_ident(cc)} {op} "
                    f"{_ident(fk.ref_table)}.{_ident(pc)}"
                )

    return "\n".join(out).rstrip() + "\n"
