"""Emit CREATE TABLE DDL from the neutral ER view.

SQL DDL is the universal interchange target: every warehouse and modeling tool ingests
it. Types come from the same platform adapter dbt uses, so the DDL matches the
generated project. Primary keys, single-column uniques, NOT NULL, and foreign-key
REFERENCES are all rendered; the dialect is selectable."""

from __future__ import annotations

from mdl_core.ir import Model
from mdl_emit_erd.model_view import Table, build_tables


def _ident(name: str, dialect: str) -> str:
    # Snowflake/warehouse identifiers are commonly unquoted upper/lower; keep it simple
    # and quote only when a name is not a plain identifier.
    if name.replace("_", "").isalnum() and not name[0].isdigit():
        return name
    q = '"' if dialect != "mysql" else "`"
    return f"{q}{name}{q}"


def emit_sql_ddl(model: Model, *, dialect: str = "postgres") -> str:
    """CREATE TABLE statements with PK/UNIQUE/NOT NULL and FK REFERENCES.

    `dialect` selects the SQL type mapping via the dbt platform adapters
    (postgres|snowflake|redshift|duckdb|...); an unknown dialect falls back to duckdb's
    generic types."""
    from mdl_emit_dbt.platforms import available_adapters, get_adapter

    adapter_name = dialect if dialect in available_adapters() else "duckdb"
    # postgres isn't a warehouse adapter; map it to duckdb's ANSI-ish types.
    if dialect == "postgres":
        adapter_name = "duckdb"
    adapter = get_adapter(adapter_name)
    tables = build_tables(model, adapter)

    out: list[str] = [f"-- SQL DDL ({dialect}) generated by Modelith", ""]
    for t in tables:
        out.extend(_table_ddl(t, dialect))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _table_ddl(t: Table, dialect: str) -> list[str]:
    lines = [f"CREATE TABLE {_ident(t.name, dialect)} ("]
    body: list[str] = []
    for c in t.columns:
        parts = [f"  {_ident(c.name, dialect)} {c.sql_type}"]
        if not c.nullable:
            parts.append("NOT NULL")
        if c.unique and c.name not in t.pk_columns:
            parts.append("UNIQUE")
        body.append(" ".join(parts))
    if t.pk_columns:
        cols = ", ".join(_ident(c, dialect) for c in t.pk_columns)
        body.append(f"  PRIMARY KEY ({cols})")
    for fk in t.foreign_keys:
        if not fk.ref_columns:
            continue  # can't write REFERENCES without the target column(s)
        cols = ", ".join(_ident(c, dialect) for c in fk.columns)
        refcols = ", ".join(_ident(c, dialect) for c in fk.ref_columns)
        body.append(
            f"  FOREIGN KEY ({cols}) REFERENCES {_ident(fk.ref_table, dialect)} ({refcols})"
        )
    lines.append(",\n".join(body))
    lines.append(");")
    # column comments (portable-ish: emit COMMENT ON for postgres/duckdb-style)
    if dialect in ("postgres", "duckdb"):
        for c in t.columns:
            if c.definition:
                safe = c.definition.replace("'", "''").strip()
                lines.append(
                    f"COMMENT ON COLUMN {_ident(t.name, dialect)}."
                    f"{_ident(c.name, dialect)} IS '{safe}';"
                )
    return lines
